spring:
    application:
        name: reviewService

    datasource:
        url: jdbc:postgresql://localhost:5432/review
        username: uthej
        password: 123456789
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
    #EUREKA
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetchRegistry: true
server:
    port: 8083