spring:
    application:
        name: configServer
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/Uthej420/application-config/
    #EUREKA
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetchRegistry: true
