spring:
#  application:
#    name: jobService

  config:
    import: "optional:configserver:http://localhost:8080"


#  profiles:
#    active: dev
  #POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: uthej
    password: 123456789
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  #EURKEA
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry: true

  #ZIPKIN
  #Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
    health:
      circuitbreakers:
        enabled: true

  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081

  #RESILIENCE4J
resilience4j:
  circuitbreaker:
    instances:
      companyBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
        eventConsumerBufferSize: 10
        maxAttempts: 5
        waitDuration: 2s
  ratelimiter:
    instances:
      companyBreaker:
        timeoutDuration: 0
        limitRefreshPeriod: 4
        limitForPeriod: 2


#  retry:
#    instances:
#      maxAttempts: 3
#      waitDuration: 2s
#      enableExponentialBackoff: true
#      exponentialBackoffMultiplier: 2
#
#  timelimiter:
#    instances:
#      timeoutDuration: 5s