spring:
  application:
    name: jobService
  #POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: uthej
    password: 123456789
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  #EURKEA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8081